services:
  - type: web
    name: coin-detector
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p model static/uploads
    startCommand: python flaskapp.py  # Or "uvicorn flaskapp:app" if using ASGI
    envVars:
      - key: PORT
        value: 10000
      - key: MODEL_PATH
        value: model/best.pt
      - key: SUPABASE_URL
        value: your_url
      - key: SUPABASE_KEY
        value: your_key