services:
  - type: web
    name: coin-detector
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p model
    startCommand: gunicorn --timeout 300 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PORT
        generateValue: true
      - key: MODEL_PATH
        value: ./model/best.pt